name: Go + PostgreSQL
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
    with:
      stable: 'false'
      go-version: '1.15.7'
    - name: Build
      run: |
        go build postgrehelper.go
        